# Generated by Django 4.0.2 on 2022-03-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupApp', '0006_alter_customer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='fname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lname',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pass1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pass2',
            field=models.CharField(default=models.CharField(max_length=500, null=True), max_length=500, null=True),
        ),
    ]
