# Generated by Django 4.0.2 on 2022-03-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupApp', '0008_alter_customer_fname_alter_customer_lname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='fname',
            field=models.CharField(default='fname', max_length=50),
        ),
    ]
