# Generated by Django 4.0.2 on 2022-03-08 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signupApp', '0014_remove_customer_pass2_alter_customer_pass1'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='login_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='logout_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='verified',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
