# Generated by Django 4.0.2 on 2022-03-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupApp', '0015_customer_login_time_customer_logout_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='login_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='logout_time',
            field=models.DateTimeField(null=True),
        ),
    ]
