# Generated by Django 3.1.5 on 2022-03-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupApp', '0016_alter_customer_login_time_alter_customer_logout_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='login_logout_logs',
        ),
    ]
