# Generated by Django 3.1.5 on 2022-03-08 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signupApp', '0017_auto_20220308_1623'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
