# Generated by Django 4.0.2 on 2022-03-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupApp', '0018_auto_20220308_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
